services:
  mongodb:
    build: ./mongodb # it moves to mongodb directory 
    image: charan1325/mongodb:1.0.0 #docker build -t charan1325mongodb:1.0.0
    container_name: mongodb


networks:
  default:
    driver: bridge
    name: roboshop
    external: false #if false ypu need to create network manually

    